### ISSUE TITLE
activeGamepad is undefined

### ISSUE THREAD

**Issue by Graxo** [e7d/gamepad-viewer#4]
Hi,

I cloned it and setup in my homelab to give it a go.
When i go to my URL i see the gamepad, but then i press a button the game pad its disappears.
And see the following error in the console of my browser: Uncaught TypeError: activeGamepad is undefined

I use Windows 11 with Firefox.
Anyone else with this issue?

Kind regards,
Graxo

**Comment by e7d** [comment]
That was a real issue that should now be fixed.
