### ISSUE TITLE
Feature request: support PS5 Gamepad

### ISSUE THREAD

**Issue by Jimmy-Min** [e7d/gamepad-viewer#6]
It would be cool if it could support the latest PS5 controller. Do you have this development idea, dear author?

**Comment by e7d** [comment]
Hi @Jimmy-Min,

Sure, that would be doable.
By supporting the PS5 controller, do you mean:
- its input being correctly detecting?
- display it's skin?

I'm currently not having a PS5 controller, thus not being able to test it's compatibility myself.

Regards.

**Comment by Jimmy-Min** [comment]
Thank you for your response. It's gamepad-viewer‘s CSS and PNG files of a PS5 controller, it may be possible to directly replace those files in the project. https://github.com/justEhCupcake/justEhCupcake.github.io/tree/main/PS5_Display_Pics

**Comment by Jimmy-Min** [comment]
> Thank you for your response. It's gamepad-viewer‘s CSS and PNG files of a PS5 controller, it may be possible to directly replace those files in the project. https://github.com/justEhCupcake/justEhCupcake.github.io/tree/main/PS5_Display_Pics

The PS5 and PS4 controllers have compatible button layouts, and only differ in their appearance. Perhaps I can help with testing.

**Comment by e7d** [comment]
> > Thank you for your response. It's gamepad-viewer‘s CSS and PNG files of a PS5 controller, it may be possible to directly replace those files in the project. https://github.com/justEhCupcake/justEhCupcake.github.io/tree/main/PS5_Display_Pics
> 
> The PS5 and PS4 controllers have compatible button layouts, and only differ in their appearance. Perhaps I can help with testing.

Hi again @Jimmy-Min 

I gave it a try. I made some small adjustments better fitting with my other skin integration, but otherwise, it should work as intended.
I did not push it to the live website yet. IN the meantime, you can test it in the beta version of the website, here: https://beta.gamepad.e7d.io/
Feel free to get back to me with your impressions.

Cheers.

**Comment by Jimmy-Min** [comment]
> > > Thank you for your response. It's gamepad-viewer‘s CSS and PNG files of a PS5 controller, it may be possible to directly replace those files in the project. https://github.com/justEhCupcake/justEhCupcake.github.io/tree/main/PS5_Display_Pics
> > 
> > 
> > The PS5 and PS4 controllers have compatible button layouts, and only differ in their appearance. Perhaps I can help with testing.
> 
> Hi again @Jimmy-Min
> 
> I gave it a try. I made some small adjustments better fitting with my other skin integration, but otherwise, it should work as intended. I did not push it to the live website yet. IN the meantime, you can test it in the beta version of the website, here: https://beta.gamepad.e7d.io/ Feel free to get back to me with your impressions.
> 
> Cheers.

Thank you very much, author. I have tried my PS5 controller and it works perfectly, mapping all the buttons and functions correctly. If possible, could you please update the code? Thank you.

**Comment by Jimmy-Min** [comment]
> > > Thank you for your response. It's gamepad-viewer‘s CSS and PNG files of a PS5 controller, it may be possible to directly replace those files in the project. https://github.com/justEhCupcake/justEhCupcake.github.io/tree/main/PS5_Display_Pics
> > 
> > 
> > The PS5 and PS4 controllers have compatible button layouts, and only differ in their appearance. Perhaps I can help with testing.
> 
> Hi again @Jimmy-Min
> 
> I gave it a try. I made some small adjustments better fitting with my other skin integration, but otherwise, it should work as intended. I did not push it to the live website yet. IN the meantime, you can test it in the beta version of the website, here: https://beta.gamepad.e7d.io/ Feel free to get back to me with your impressions.
> 
> Cheers.

**Comment by Jimmy-Min** [comment]
> > > Thank you for your response. It's gamepad-viewer‘s CSS and PNG files of a PS5 controller, it may be possible to directly replace those files in the project. https://github.com/justEhCupcake/justEhCupcake.github.io/tree/main/PS5_Display_Pics
> > 
> > 
> > The PS5 and PS4 controllers have compatible button layouts, and only differ in their appearance. Perhaps I can help with testing.
> 
> Hi again @Jimmy-Min
> 
> I gave it a try. I made some small adjustments better fitting with my other skin integration, but otherwise, it should work as intended. I did not push it to the live website yet. IN the meantime, you can test it in the beta version of the website, here: https://beta.gamepad.e7d.io/ Feel free to get back to me with your impressions.
> 
> Cheers.

Thank you very much, author. I have tried my PS5 controller and it works perfectly, mapping all the buttons and functions correctly. And I tested it on the "develop" branch, and it's really cool. Thank you.

**Comment by e7d** [comment]
Hey @Jimmy-Min ,

Glad to hear it suits your needs. I would need a few more days to stabilize some other features I'm working on, and then it should be ready to hit public stable release on gamepad.e7d.io.
i'll try and drop you a message here when it will be live.

Regards.
